apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  USERNAME: {{ .Values.secretUsername | b64enc }}
  PASSWORD: {{ .Values.secretPassword | b64enc }}
