apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  labels:
    app: "{{ .Values.app.name }}"
type: Opaque
data:
  USERNAME: "{{ .Values.vault.username | b64enc }}"
  PASSWORD: "{{ .Values.vault.password | b64enc }}"


