apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  annotations:
    avp.kubernetes.io/path: "secret/data/devwebapp/config"
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  # USERNAME: {{ .Values.secretUsername | b64enc }}
  # PASSWORD: {{ .Values.secretPassword | b64enc }}
  USERNAME: <username>
  PASSWORD: <password>
