apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
  annotations:
    avp.kubernetes.io/path: "secret/data/devwebapp/config"
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  USERNAME: "{{ .Values.vault.username | b64enc }}"
  PASSWORD: "{{ .Values.vault.password | b64enc }}"

